---
- name: Ensure GPG key
  become: true
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
  when: ansible_os_family == "Debian"
- name: Ensure docker repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
  when: ansible_distribution == "Ubuntu"
- name: Install docker-ce
  become: true
  apt:
    name: docker-ce
    state: present
  when: ansible_os_family == "Debian"
- name: Install docker-py
  become: true
  pip:
    name: docker
    state: present
